site_name: myevan.net
theme: material
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
pages:
    - "home": index.md
    - "tutorials": 
        - "myevan site": myevan_site_tutorial.md
        - "ue4 build": ue4_build_tutorial.md
    - "digests":
        - "windows":
            - "git hosting": windows_git_hosting_digest.md
        - "ue4":
            - "setup": ue4_setup_digest.md
            - "vs settings": ue4_vs_settings_digest.md
        - "vs2015":
            - "setup": vs2015_setup_digest.md
        - "vscode":
            - "plugins": 
                - "vim": vscode_plugin_vim_digest.md
    - "issues":
        - "ue4":
            - "vs gitignore": github_ext_for_vs_ue4_gitignore_issue.md
