site_name: myevan.net
theme: material
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
pages:
    - "home": index.md
    - "tutorials": 
        - "myevan site": myevan_site_tutorial.md
