site_name: myevan.net
theme: material
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
pages:
    - "home": index.md
    - "tutorials": 
        - "myevan site": myevan_site_tutorial.md
        - "ue4 build": ue4_build_tutorial.md
    - "digests":
        - "windows":
            - "git hosting": windows_git_hosting.md
        - "ue4":
            - "setup": ue4_setup_digest.md
