site_name: myevan.net
theme: material
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
pages:
    - "home": index.md
    - "tutorials": 
        - "myevan site": myevan_site_tutorial.md
        - "ue4 build": ue4_windows_build_tutorial.md
        - "git swarm": 
            - "installation": gitswarm_installation_ubuntu_tutorial.md
    - "digests":
        - "vcs":
            - "git":
                - "git hosting": git_windows_hosting_digest.md
                - "git swarm": 
                    - "requirements": gitswarm_requirements_digest.md
                    - "administration": gitswarm_administration_digest.md
            - "perforce":
                - "svn migration": perforce_windows_svn_migration_digest.md
        - "ue4":
            - "vs setup": ue4_windows_vs_setup_digest.md
            - "boost compile time": ue4_boost_compile_times_digest.md
        - "vs2015":
            - "download": vs2015_download_digest.md
        - "vscode":
            - "vim plugin": vscode_plugin_vim_digest.md
        - "vmware":
            - "static ip": vmware_fusion_8_static_ip_digest.md
            - "port forwarding": vmware_fusion_8_port_forwarding_digest.md
    - "issues":
        - "ue4":
            - "vs ext": ue4_windows_vs_git_ext_gitignore_issue.md
        - "gitswarm":
            - "helix mirror": gitswarm_helix_mirror_repository_delete_issue.md
    - "analysis":
        - "ue4":
            - "setup script": ue4_setup_script_analysis.md
            - "build tool":
                - "processor count multiplier": ue4_processor_count_multiplier_analysis.md
                - "faster without unity": ue4_faster_without_unity_analysis.md
                - "min files using precompiled header": ue4_min_files_using_precompiled_header_analysis.md

