site_name: myevan.net
theme: material
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
pages:
    - "home": index.md
    - "setup":
        - "windows":
            - "system":
                - "package": windows_package_mgr_choco.md
                - "hangul": windows_hangul_key_capslock.md
                - "remote desktop": windows_remote_desktop_port.md
                - "virtualenv": windows_python_virtualenv.md
            - "editor":
                - "vscode":
                    - "python": windows_vscode_python_virtualenv.md
            - "tool": 
                - "mkdocs": windows_python_mkdocs.md
        - "mac":
            - "system":
                - "package": mac_package_mgr_homebrew.md
                - "hangul": mac_hangul_key_capslock.md
                - "enable root": mac_root_enable.md
                - "hostname": mac_terminal_hostname.md
            - "python":
                - "pyenv": mac_python_pyenv.md
                - "virtualenv": 
                    - "wrapper": mac_python_virtualenvwrapper.md
            - "tool": 
                - "xcode": mac_xcode_command_line.md
        - "xplatform":
            - "vscode plugin":
                - "vim": vscode_plugin_vim.md
        - "github.io": 
            - "mkdocs": github_io_mkdocs.md
            - "custom domain": github_io_custom_domain.md

    - "tutorial":
        - "ue4 build": ue4_windows_build.md
        - "hyper-v":
            - "ubuntu":
                - "installation": hyper_v_ubuntu_installation.md
                - "disk expanding": hyper_v_ubuntu_disk_expanding.md
        - "ubuntu":
            - "ip": ubuntu_setup_ip.md
    - "digest":
        - "*nix":
            - "screen": screen.md
        - "vcs":
            - "git":
                - "git bash prompt": git_bash_prompt.md
                - "git hosting": git_windows_hosting.md
                - "git lab": 
                    - "installation": gitlab_ubuntu_installation.md
                - "git swarm": 
                    - "requirements": helix_gitswarm_requirements.md
                    - "installation": helix_gitswarm_ubuntu_installation.md
                    - "administration": helix_gitswarm_ubuntu_administration.md
            - "helix":
                - "svn migration": helix_perforce_windows_svn_migration.md
                - "perforce daemon": helix_perforce_windows_daemon.md
                - "perforce service": helix_perforce_windows_service.md
        - "ue4":
            - "vs setup": ue4_windows_vs_setup.md
            - "boost compile time": ue4_boost_compile_times.md
            - "dedicated": ue4_dedicated_server.md
        - "vs2015":
            - "download": vs2015_download.md
        - "vmware":
            - "static ip": vmware_fusion_8_static_ip.md
            - "port forwarding": vmware_fusion_8_port_forwarding.md
    - "issue":
        - "ue4":
            - "vs ext": ue4_windows_vs_git_ext_gitignore.md
        - "helix":
            - "gitswarm mirror": helix_gitswarm_ubuntu_mirror_repository_delete.md
    - "analysis":
        - "ue4":
            - "setup script": ue4_setup_script.md
            - "build tool":
                - "processor count multiplier": ue4_processor_count_multiplier.md
                - "faster without unity": ue4_faster_without_unity.md
                - "min files using precompiled header": ue4_min_files_using_precompiled_header.md

