site_name: myevan.net
theme: material
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
pages:
    - "home": index.md
    - "tutorials": 
        - "myevan site": myevan_site_tutorial.md
        - "ue4 build": 
            - "windows": windows_ue4_build_tutorial.md
    - "digests":
        - "git":
            - "git hosting": windows_git_hosting_digest.md
        - "ue4":
            - "setup": 
                - "vs": windows_ue4_setup_vs_digest.md
                - "boost compile time": ue4_boost_compile_times_digest.md
        - "vs2015":
            - "download": vs2015_download_digest.md
        - "vscode":
            - "plugins": 
                - "vim": vscode_plugin_vim_digest.md
    - "issues":
        - "ue4":
            - "vs gitignore": github_ext_for_vs_ue4_gitignore_issue.md
    - "analysis":
        - "ue4":
            - "setup script": ue4_setup_script_analysis.md
            - "processor count multiplier": ue4_processor_count_multiplier_analysis.md

